### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xellDart** [masterwok/simple-torrent-android#1]
I got this error when download torrent:
08-20 20:20:19.330 9251-9251/com.sharetv.xperiafan13.androidtv I/TORRENT: https://www.elitetorrent.biz/wp-content/uploads/files/1534528102-Todos%20chicos%20que%20enamore%20[1080p][Latino][wWw.EliteTorrent.BiZ].torrent
08-20 20:20:19.480 9251-9251/com.sharetv.xperiafan13.androidtv E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sharetv.xperiafan13.androidtv, PID: 9251
    android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1460)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:102)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
        at java.net.InetAddress.getAllByName(InetAddress.java:787)
        at com.android.okhttp.Dns$1.lookup(Dns.java:39)
        at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
        at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
        at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(Unknown Source:0)
        at com.masterwok.simpletorrentandroid.TorrentSession.downloadUsingNetworkUri(TorrentSession.kt:310)
        at com.masterwok.simpletorrentandroid.TorrentSession.start(TorrentSession.kt:431)
        at com.sharetv.xperiafan13.androidtv.utils.TorrentDownloader.download(TorrentDownloader.kt:41)
        at com.sharetv.xperiafan13.androidtv.views.TorrentActivity$createDialog$1.onClick(TorrentActivity.kt:91)
        at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1168)
        at android.widget.AdapterView.performItemClick(AdapterView.java:321)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1217)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3203)
        at android.widget.AbsListView$3.run(AbsListView.java:4151)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

My code:
class TorrentDownloader {
    
    fun download(data: String, directory: File, context: Context) {
        Log.i("TORRENT", data)
        val torrentUri = Uri.parse(data)

        val torrentSessionOptions = TorrentSessionOptions(
                downloadLocation = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
                , onlyDownloadLargestFile = true
                , enableLogging = false
                , shouldStream = true
        )
        val torrentSession = TorrentSession(torrentSessionOptions)
        torrentSession.start(context, torrentUri)
    }
}

**Comment by masterwok** [comment]
The call to ```torrentSession.start(context, torrentUri)``` is failing because it's being called on the main thread. If you look at your stack trace, there is a [NetworkOnMainThreadException](https://developer.android.com/reference/android/os/NetworkOnMainThreadException)  occurring. To fix it, make sure to always call that method on a background thread. 

A quick and dirty fix to see if this works would be to do:

```kotlin
AsyncTask.execute { torrentSession.start(context, torrentUri) }
```

Thanks for pointing this out, I will add a comment in the documentation.

**Comment by xellDart** [comment]
Thanks!, already solved!

**Comment by masterwok** [comment]
Sweet, glad it worked out!
